/**
 * FeedbackForm — Submit subpage
 *
 * WRITE path (fire-and-forget):
 *   POST /feedback → API Gateway → Lambda #1 → SNS → SQS
 *   Lambda #1 returns 202 immediately. Processing continues async via
 *   Lambda #2 → Bedrock → DynamoDB. No polling here — check
 *   the Recommendations tab once processing is complete.
 */
import { useState } from 'react';
import { API_URL, authHeader } from '../lib/aws';

export default function FeedbackForm() {
  const [text,     setText]     = useState('');
  const [status,   setStatus]   = useState('idle');
  // idle | submitting | sent | error
  const [errorMsg, setErrorMsg] = useState('');

  async function handleSubmit(e) {
    e.preventDefault();
    const trimmed = text.trim();
    if (!trimmed) return;

    setStatus('submitting');
    setErrorMsg('');

    if (!API_URL) {
      setErrorMsg(
        'REACT_APP_API_URL is not configured. ' +
        'If running locally: copy .env.example to .env.local and fill in the value. ' +
        'If deployed on Amplify: add REACT_APP_API_URL in Amplify Console → Environment variables, ' +
        'then redeploy (env vars are baked in at build time — a new build is required).'
      );
      setStatus('error');
      return;
    }

    try {
      const res = await fetch(`${API_URL}/feedback`, {
        method:  'POST',
        headers: { ...(await authHeader()), 'Content-Type': 'application/json' },
        body:    JSON.stringify({ feedback_text: trimmed }),
      });

      if (res.status === 202) {
        setText('');
        setStatus('sent');
      } else {
        const err = await res.json().catch(() => ({}));
        setErrorMsg(err.error || `Unexpected status ${res.status}`);
        setStatus('error');
      }
    } catch {
      setErrorMsg('Network error — please try again.');
      setStatus('error');
    }
  }

  const isSubmitting = status === 'submitting';

  return (
    <div>
      <div className="page-header">
        <h2 className="page-title">Submit Feedback</h2>
        <p className="page-desc">
          Paste feedback you received and get an AI-generated career action plan.
        </p>
      </div>

      <div className="card">
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label className="form-label" htmlFor="feedback-text">
              Feedback you received
            </label>
            <textarea
              id="feedback-text"
              className="form-textarea"
              value={text}
              onChange={e => { setText(e.target.value); if (status === 'sent') setStatus('idle'); }}
              placeholder="e.g. You need to improve communication with the team and take more ownership in meetings…"
              disabled={isSubmitting}
              rows={5}
            />
          </div>

          <div className="status-row">
            <button
              type="submit"
              className="btn btn-primary"
              disabled={!text.trim() || isSubmitting}
            >
              {isSubmitting ? 'Submitting…' : 'Get AI Recommendation'}
            </button>
          </div>

          {status === 'error' && (
            <p className="error-msg">{errorMsg}</p>
          )}
        </form>
      </div>

      {/* ── Fire-and-forget confirmation banner ── */}
      {status === 'sent' && (
        <div className="sent-banner">
          <span className="sent-icon">✓</span>
          <div>
            <strong>Feedback submitted!</strong>
            <p>
              Your recommendation is being generated by AI. It usually takes 15–30 seconds.
              Check the <strong>My Recommendations</strong> tab when ready.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
